title: "Biuro Rachunkowe Magdalena Brzuchalska"
description: "Biuro rachunkowe w Redzie dla małych firm i placówek oświatowych. KPiR, ryczałt, kadry i płace oraz rozliczanie dotacji. Obsługa Redy, Rumii i Wejherowa."
theme: jekyll-theme-cayman
lang: pl-PL
url: "https://brzuchalska.com"

plugins:
  - jekyll-seo-tag

kramdown:
  parse_block_html: true
