title: Biuro Rachunkowe Magdalena Brzuchalski
description: Profesjonalne usługi księgowe i kadrowe dla małych firm, przedszkoli i żłobków. Specjalizacja w KPiR, ryczałcie oraz rozliczeniach dotacji gminnych.
theme: jekyll-theme-cayman
